### ISSUE TITLE
Section to add tool provider

### ISSUE THREAD

**Issue by rakurame96** [iDoka/awesome-canbus#16]
It is good to add a section comprising tool suppliers like Vector Informatik, Intrepid Control Systems, Peak Systems, ControlTec, etc to this list. 

Can create a pull request if you need any help on this.

**Comment by iDoka** [comment]
In my opinion, adding commercial tools is contrary to the spirit of this list - to collect free/opensourced items in one place.

The tools which already on the list cover most enthusiasts' needs.
