### ISSUE TITLE
Additional tool for your list

### ISSUE THREAD

**Issue by ctuesley** [iDoka/awesome-canbus#2]
Hi iDoka,

                 Great list, really the best single collection of resources I've found on CanBUS and I've got it bookmarked.  I'm part of a startup that is now creating tools in this space and I was wondering if you would be kind enough to add us to your list of tools.

Our GUI tool is called Profinity, it supports DBC, basic Can management, logging to file as well as time series databases like InfluxDB and Prometheus as well as thing we call Cloud Connect which allows you to stream CanBUS to teams of people in near real time.

https://www.prohelion.com/software/
https://docs.prohelion.com/Profinity/Overview.html

It's free for general use, currently it is Windows only but there will be a Unix release later this year that also supports scripting in Python C# and F# as well as a console only mode.

We are also taking over the production of Tritiums Can to Ethernet bridge as well and that's coming to market in the next month or so as well as a Can to USB bridge. Our background is in Electric Vehicle motorsport so most of our products are focused in that space at the moment but Profinity is a general purpose tool that can be used for any CanBUS based scenario.

Profinity supports our own bridges as well as SocketCan via https://github.com/linux-can/socketcand

Any questions just let me know.  Obviously your right across this space so if you have any suggestion on the tool I'd be keen to hear them as well.

Cheers,

Cameron.

**Comment by iDoka** [comment]
#wontfix
