### ISSUE TITLE
Your missing the largest canbus hacking  ecosystem. Comma panda and cabana.

### ISSUE THREAD

**Issue by ryleymcc** [iDoka/awesome-canbus#20]
Using a panda with cabana provides the best RE and development suites for canbus. It is free and open-source and is used by thousands of hackers and developer's.

**Comment by ryleymcc** [comment]
Your also missing plotjuggler. With panda hardware, cabana and plotjuggler, you can quickly RE the entire car in a few days.

**Comment by ryleymcc** [comment]
You may as well add the comma 2. Its made for driving but it has the panda built in and it's a full computer you can program with python and run scripts to intercept and emulate CAN devices.

**Comment by iDoka** [comment]
@ryleymcc thanks for contributing this list and sharing your experience.
I'll adding it soon

**Comment by iDoka** [comment]
@ryleymcc I added everything except  "comma 2". Could you help me with references and right description for  "comma 2"?

**Comment by MoreTore** [comment]
https://comma.ai/shop
