### ISSUE TITLE
Vector VXL python wrapper project addition proposal

### ISSUE THREAD

**Issue by KhazAkar** [iDoka/awesome-canbus#24]
Hi,
I just found today complete Vector VXL python wrapper, windows only, but should be interesting, since it wraps not only CANbus, but also other supported protocols like MOST, Ethernet channel/network and more

[PythonVectorXL](https://github.com/Prindl/PythonVectorXL)

**Comment by iDoka** [comment]
[Damian](https://github.com/KhazAkar), thanks for you contribution.
I just added this item, please check: https://github.com/iDoka/awesome-canbus/commit/d15eb7b1de59cf9590b75e87ddd6479a781a6c53
Any feedback are welcome. If description is okay you could close this issue.

**Comment by KhazAkar** [comment]
Looks okay, thanks a lot!
