### ISSUE TITLE
Add TWAI_SLCAN for ESP32-S3

### ISSUE THREAD

**Issue by Pacerino** [iDoka/awesome-canbus#25]
I'm following this repo a long time now. Because of that i've recently bought a RejsaCAN. Unfortunately i had to realise that a lot of the stuff out there isnt working anymore. Therefore i've created a quick and dirty implementation of SLCAN for the ESP32-S3 with TWAI.

I think this is something for this list.
https://github.com/Pacerino/TWAI_SLCAN

Anyway thank you for creating this awesome list!

**Comment by iDoka** [comment]
Added to the list.
BTW, would be great to add in README explanation of purpose of BLUE_LED, YELLOW_LED.

**Comment by Pacerino** [comment]
Thanks for the merge! I've added the explanation of the LEDs to the Readme!
