### ISSUE TITLE
Some new stuff :-)

### ISSUE THREAD

**Issue by MagnusThome** [iDoka/awesome-canbus#27]
@iDoka 

I hacked ESP32RET so it also works with ESP32-S3 which doesn't have classic serial over bluetooth
https://github.com/MagnusThome/ESP32S3RET

I also added a simplified OBD2 layer to run on top of the esp32_can library that supports the newer ESP32-S3 (that sandeeps library doesn't (at least yet)). It's a fork and rewrite of sandeep's OBD2 code
https://github.com/MagnusThome/esp32_obd2

I also made a VERY simple OBD2 car emulator which runs on ESP32-S3 and the like (with the esp32_can library)
https://github.com/MagnusThome/ESP32_OBD2_Emulator

Finally mostly just a fun "first": example code that is tested and runs on the new ESP32-C6 that has TWO built in CAN controllers :-)
https://github.com/MagnusThome/RejsaCAN-ESP32/tree/main/Code%20Examples/RejsaCAN%20v6.x%20-%20ESP32-C6%20-%20DUAL%20CAN%20self%20test

**Comment by iDoka** [comment]
Well done, Magnus!
Thanks for you effort 🙏

For me supporting two built-in CAN on ESP32-C6 is the most promising things 😍
