### ISSUE TITLE
Newbie Qs about J2534 and linux hardware

### ISSUE THREAD

**Issue by Strykar** [iDoka/awesome-canbus#30]
I am looking to sniff the CANBUS on a 2011 (1KD-FTV) Toyota, which uses SAE J2534 and [this](https://www.vxdiagshop.com/wholesale/vxdiag-vcx-nano-for-toyota-wifi-version.html) is one of the few dongles that works with it and Techstream.

What hardware (preferably with RS232, or ethernet / wifi) can I use that runs linux and will show up on the network as can0 or something so I can sniff the protocol easily?

**Comment by iDoka** [comment]
won't fix

**Comment by Strykar** [comment]
@iDoka Uhm, may I ask why not?
Would you mind enabling the Discussion feature so folks may pose Qs there instead of GH Issues?

**Comment by atomicdog** [comment]
There's plenty of other places to have discussions on CAN. It probably wouldn't have much traffic here so most questions wouldn't get answered anyways.

**Comment by Strykar** [comment]
> There's plenty of other places to have discussions on CAN. It probably wouldn't have much traffic here so most questions wouldn't get answered anyways.

Nice, mind sharing a few?
There's none on IRC for CAN, I found two forums, and my Q on r/HackingCars had one person respond.

**Comment by italocjs** [comment]
> > There's plenty of other places to have discussions on CAN. It probably wouldn't have much traffic here so most questions wouldn't get answered anyways.
> 
> Nice, mind sharing a few? There's none on IRC for CAN, I found two forums, and my Q on r/HackingCars had one person respond.

if you find i'd love to know, so far i didnt find any active can forum.

**Comment by atomicdog** [comment]
On Discord there's [1BitSquared](https://discord.gg/hC4499US) and [RECESSIM](https://discord.gg/Q9efqMPw)
