### ISSUE TITLE
Emulating ELM327 

### ISSUE THREAD

**Issue by MagnusThome** [iDoka/awesome-canbus#5]
I've been looking for ways of getting an ESP32 or other hardware to work as an ELM327 USB dongle.

The only I've found so far is using ESP32RET that actually also includes sort of beta ELM327 functionality support.

Ever seen any other attempts?

**Comment by iDoka** [comment]
Magnus, 
I don't think ELM327 [server]-functionality is hardware dependent.
I can borrow ELM327 engine codebase from another HW-platform, e.g. [ARM-based uC](https://github.com/iDoka/awesome-canbus#arm).

PS: Unfortunately awesome project [Open-source ELM329 OBD adapter based on STM32F042](https://github.com/ObdDiag-Net/elm329) unavailable now by unknown reason.

**Comment by MagnusThome** [comment]
I agree, it can be run on any processor like in https://github.com/collin80/ESP32RET where there's some basic ELM327/ELM329 support included on a ESP32. And the STM32 based project you linked to also. Wonder why it's taken down :-(

Odd I can't find any more similar projects though?


/Magnus


PS: Probably not for your awesome list but just FYI, I made a small board for myself and added info here on github about it, some basic code examples and inspiration: https://github.com/MagnusThome

**Comment by Alia5** [comment]
https://github.com/HongjieMaTJU/elm329
